<?php

/**
 * @file
 * Contains cubic_people.module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function cubic_people_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  /* @var \Drupal\node\Entity\Node $node */
  $node = $route_match->getParameter('node');
  if (is_a($node, '\Drupal\node\Entity\Node') && $node->bundle() === 'person' && $node->hasField('field_role') && !$node->get('field_role')->isEmpty()) {
    /* @var \Drupal\taxonomy\Entity\Term $role */
    $role = $node->get('field_role')->first()->entity;

    if ($role && $role->id()) {
      $options = [
        'query' => [
          'role' => $role->id(),
        ],
      ];

      $url = Url::fromRoute('view.people_teaser_list.all_people', [], $options);
      $link = Link::fromTextAndUrl($role->getName(), $url);
      $breadcrumb->addLink($link);
    }
  }
}
