<?php

/**
 * @file
 * Custom bh_global_nav module.
 */

/**
 * Implements hook_preprocess_menu().
 */
function bh_global_nav_preprocess_menu(&$vars) {
  if ($vars['menu_name'] == 'main-mega-navigation') {
    $vars['#attached']['library'][] = 'bh_global_nav/bh-menu-js';
  }
  if ($vars['menu_name'] == 'mega-footer') {
    $vars['#attached']['library'][] = 'bh_global_nav/bh-menu-footer-js';
  }
}
