<?php

/**
 * @file
 * Contains cubic_search.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cubic_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cubic_search module.
    case 'help.page.cubic_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search Integration/helpers for Cubic') . '</p>';
      return $output;

    default:
  }
}
